# Generated by Django 3.0.7 on 2020-12-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201118_0606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
